### ISSUE TITLE
Make it possible to not rely on a private, global `leasewebClient`

### ISSUE THREAD

**Issue by Szymongib** [Leaseweb/leaseweb-go-sdk#67]
### Problem 

Currently to use the SDK one needs to call `InitLeasewebClient` which initializes the private `leasewebClient` struct as a global variable which is then used by other structs like `DedicatedServerApi` to execute requests.

This approach makes it hard to work with multiple accounts (and API keys) as from my understanding, I would need to call `InitLeasewebClient` each time I want to switch the API key used, which makes unnecessary initialization of a new HTTP client each time.

Furthermore given that it is a global variable it prevents any concurrency usage across different accounts' API requests.

### Possible solution

Make it possible to initialize `LeasewebClient` from the outside instead of relying on a global variable. This would require some changes to all APIs clients as now those would need to reference an instance of `LeasewebClient`. For ease of use for some people globally initialized client can be a default (it is a pattern a lot of libraries follow).

**Comment by majidkarimizadeh** [comment]
Hi @Szymongib and thanks for reporting and came up with the solution!

At the moment, I don't have any plan to support multiple clients for this SDK, but maybe in future!
BTW, I would appreciate any PR regarding this issue!

**Comment by Szymongib** [comment]
Hey, thanks for the response. Will try to draft a PR when have a bit more time.
