### ISSUE TITLE
Wiki pages are outdated

### ISSUE THREAD

**Issue by majidkarimizadeh** [Leaseweb/leaseweb-go-sdk#75]
@tardypad As we merged the #74 PR, the wiki pages and README file are outdated! so I'll create this issue to update the docs!
I would appreciate if you can find a way to generate docs automatically!

**Comment by tardypad** [comment]
Sorry, I forgot to update the README indeed.
I didn't know about those wiki pages though.

Personally I don't find any value in maintaining such a documentation in a wiki.
If you want to have some more details for each struct/function/... and have some examples, they should be added to the code in the repository in the standard Go way. Then everything will appear automatically in https://pkg.go.dev/github.com/LeaseWeb/leaseweb-go-sdk. This is where the users of the SDK will naturally expect to find all that information.
